name: Publish

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Release
        run: |
          python -m venv venv_python3-sdk
          VIRTUAL_ENV_DISABLE_PROMPT=1 source venv_python3-sdk/bin/activate
          pip install .
          pip install build
          pip install pip-tools
          python3 -m pip install --upgrade twine
          sh run.sh
          python -m build
          pip-compile pyproject.toml --resolver=backtracking
          echo "${PYPIRC_TOKEN}" | base64 --decode > pypirc
          python -m twine upload --config-file pypirc  dist/*
          
